"""empty message

Revision ID: 01b5719d0bda
Revises: 38523fafb3a6
Create Date: 2019-04-02 22:40:38.983687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b5719d0bda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profileImageUrl', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profileImageUrl')
    # ### end Alembic commands ###
