"""empty message

Revision ID: 02f408281d36
Revises: ceb16dfcf725
Create Date: 2019-04-21 22:23:24.669895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02f408281d36'
down_revision = 'ceb16dfcf725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('travelcards', 'isDelete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('travelcards', 'title')
    op.add_column('travels', sa.Column('imageName', sa.String(length=32), nullable=True))
    op.add_column('travels', sa.Column('imageUrl', sa.String(length=128), nullable=True))
    op.alter_column('travels', 'isDelete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('travels', 'share',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('travels', 'backgroundImageName')
    op.drop_column('travels', 'backgroundImageUrl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travels', sa.Column('backgroundImageUrl', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('travels', sa.Column('backgroundImageName', mysql.VARCHAR(length=32), nullable=True))
    op.alter_column('travels', 'share',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('travels', 'isDelete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('travels', 'imageUrl')
    op.drop_column('travels', 'imageName')
    op.add_column('travelcards', sa.Column('title', mysql.VARCHAR(length=32), nullable=True))
    op.alter_column('travelcards', 'isDelete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
