"""empty message

Revision ID: 1f01e26b0d9c
Revises: 89f54e02f931
Create Date: 2019-03-30 17:11:02.895442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f01e26b0d9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authtokens', 'token',
               existing_type=mysql.VARCHAR(length=126),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authtokens', 'token',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=126),
               existing_nullable=True)
    # ### end Alembic commands ###
