"""empty message

Revision ID: 38523fafb3a6
Revises: 843fdf309ad0
Create Date: 2019-03-31 21:55:45.111985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38523fafb3a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('token', table_name='authtokens')
    op.drop_table('authtokens')
    op.add_column('users', sa.Column('token', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'users', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'token')
    op.create_table('authtokens',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('token', mysql.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='authtokens_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('token', 'authtokens', ['token'], unique=True)
    # ### end Alembic commands ###
