"""empty message

Revision ID: 7afded5be89c
Revises: 7e87b10ea07d
Create Date: 2019-04-21 21:40:15.222329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7afded5be89c'
down_revision = '7e87b10ea07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travelcards', sa.Column('localId', sa.Integer(), nullable=False))
    op.add_column('travelcards', sa.Column('travelLocalId', sa.Integer(), nullable=False))
    op.alter_column('travelcards', 'isDelete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('travels', sa.Column('localId', sa.Integer(), nullable=False))
    op.add_column('travels', sa.Column('travelKind', sa.Integer(), nullable=True))
    op.alter_column('travels', 'isDelete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('travels', 'share',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('travels', 'travelType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travels', sa.Column('travelType', mysql.VARCHAR(length=16), nullable=True))
    op.alter_column('travels', 'share',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('travels', 'isDelete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('travels', 'travelKind')
    op.drop_column('travels', 'localId')
    op.alter_column('travelcards', 'isDelete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('travelcards', 'travelLocalId')
    op.drop_column('travelcards', 'localId')
    # ### end Alembic commands ###
