"""empty message

Revision ID: a7985ba5e1e0
Revises: 02f408281d36
Create Date: 2019-04-25 10:05:03.842753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7985ba5e1e0'
down_revision = '02f408281d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travelcards', sa.Column('theme', sa.PickleType(), nullable=True))
    op.alter_column('travelcards', 'imageName',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.PickleType(),
               existing_nullable=True)
    op.alter_column('travelcards', 'imageUrl',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.PickleType(),
               existing_nullable=True)
    op.alter_column('travelcards', 'isDelete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('travels', sa.Column('area', sa.PickleType(), nullable=True))
    op.alter_column('travels', 'isDelete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('travels', 'share',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('travels', 'entireCountry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travels', sa.Column('entireCountry', sa.BLOB(), nullable=True))
    op.alter_column('travels', 'share',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('travels', 'isDelete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('travels', 'area')
    op.alter_column('travelcards', 'isDelete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('travelcards', 'imageUrl',
               existing_type=sa.PickleType(),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('travelcards', 'imageName',
               existing_type=sa.PickleType(),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.drop_column('travelcards', 'theme')
    # ### end Alembic commands ###
